### ISSUE TITLE
The int main doesn't run twice in a row

### ISSUE THREAD

**Issue by ViktoriyaKaleva** [GeorgiaCharalampous/SpiceMate#11]
The vibro initialisation fails. It throws an error message that it can't read from the register.

**Comment by HasiVS** [comment]
I think this might be caused by the nature of the Vibro4 Click's I2C Watchdog Timer.

According to it's [Datasheet](https://github.com/GeorgiaCharalampous/SpiceMate/files/14971055/Datasheet.drv2605l.pdf), the watchdog normally clears I2C commands leftover from previous executions but in Standby Mode it can't do that.

Try removing the command to assert the Standby bit of the Mode Register (0x01) in the stop() function?
Instead, we can de-assert the GO bit which is functionally equivalent to asserting the Standb bit because it stops any active driver tasks.

**Comment by ViktoriyaKaleva** [comment]
That worked! It is now running without issues.
